IF OBJECT_ID('dbo.Roles','U') IS NULL
BEGIN
 CREATE TABLE dbo.Roles(Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(40) NOT NULL UNIQUE);
 INSERT dbo.Roles(Name) VALUES('Administrator'),('Technician'),('Viewer');
 CREATE TABLE dbo.Users(Id INT IDENTITY PRIMARY KEY, Username NVARCHAR(50) NOT NULL UNIQUE, DisplayName NVARCHAR(100) NOT NULL, PasswordHash VARBINARY(64) NOT NULL, PasswordSalt VARBINARY(64) NOT NULL, RoleId INT NOT NULL REFERENCES dbo.Roles(Id), IsActive BIT NOT NULL DEFAULT 1, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
 CREATE TABLE dbo.Personnel(Id INT IDENTITY PRIMARY KEY, FullName NVARCHAR(100) NOT NULL, Department NVARCHAR(100) NULL, Phone NVARCHAR(30) NULL, IsActive BIT NOT NULL DEFAULT 1);
 CREATE TABLE dbo.Equipment(Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(100) NOT NULL, SerialNumber NVARCHAR(30) NOT NULL UNIQUE, EquipmentType NVARCHAR(30) NOT NULL, Status NVARCHAR(30) NOT NULL DEFAULT 'Available', Notes NVARCHAR(500) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
 CREATE TABLE dbo.Checkouts(Id INT IDENTITY PRIMARY KEY, EquipmentId INT NOT NULL REFERENCES dbo.Equipment(Id), PersonnelId INT NOT NULL REFERENCES dbo.Personnel(Id), CheckedOutByUserId INT NOT NULL REFERENCES dbo.Users(Id), CheckedOutAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), DueAt DATETIME2 NOT NULL, ReturnedAt DATETIME2 NULL, ReturnNotes NVARCHAR(500) NULL);
 CREATE TABLE dbo.MaintenanceRecords(Id INT IDENTITY PRIMARY KEY, EquipmentId INT NOT NULL REFERENCES dbo.Equipment(Id), OpenedByUserId INT NOT NULL REFERENCES dbo.Users(Id), Description NVARCHAR(500) NOT NULL, OpenedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CompletedAt DATETIME2 NULL, Result NVARCHAR(500) NULL);
 CREATE TABLE dbo.Missions(Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(100) NOT NULL, Description NVARCHAR(500) NULL, PlannedAt DATETIME2 NOT NULL, Status NVARCHAR(30) NOT NULL DEFAULT 'Planned', CreatedByUserId INT NOT NULL REFERENCES dbo.Users(Id));
 CREATE TABLE dbo.MissionEquipment(MissionId INT NOT NULL REFERENCES dbo.Missions(Id), EquipmentId INT NOT NULL REFERENCES dbo.Equipment(Id), CONSTRAINT PK_MissionEquipment PRIMARY KEY(MissionId,EquipmentId));
 CREATE TABLE dbo.AuditLogs(Id BIGINT IDENTITY PRIMARY KEY, UserId INT NULL, Action NVARCHAR(50) NOT NULL, EntityName NVARCHAR(50) NOT NULL, EntityId INT NULL, Detail NVARCHAR(1000) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
END;
GO
